name: CI

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  lint-test-compile-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.0'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint:fix

      - name: Run tests
        run: npm test

      - name: Compile TypeScript
        run: npm run compile

      - name: Format code
        run: npm run format
